### ISSUE TITLE
db.collection is not a function

### ISSUE THREAD

**Issue by rashmitpankhania** [vasansr/pro-mern-stack#49]
whenever retrieving data from database, by using the latest mongodb package throws error but the previous version of mongodb 2.2.33 works perfect so it should change in package.json

**Comment by xinyili** [comment]
I never feel it's a great idea downgrading to a previous version to solve some incompatible issue.

According to the [changelog](https://github.com/mongodb/node-mongodb-native/blob/3.0/CHANGES_3.0.0.md) for 3.0.0, `MongoClient.connect`  only returns the instance rather than a database object.

So basically, in the case you only have to change from 
`db = connection;`  to
`db = connection.db('dbname');`

Good luck!

**Comment by rashmitpankhania** [comment]
thank you that really helped me
