### ISSUE TITLE
Chapter 2: babel command not found 

### ISSUE THREAD

**Issue by arrmixer** [vasansr/pro-mern-stack#8]
after i installed the babel-cli, the babel command is not found. I tried to manually install the .babelrc with the presets but when I change the the html file to reflect the /App.js the page is blank. 

I'm making the assumption the cmd babel src --presets react --out-dir static creates the App.js automatically?

please advised ... oh i'm using a Mac with Sierra 10.12.5

this is what is in my babel file 
cat babel
#!/usr/bin/env node

require("../lib/babel");

i tried this since it's a script
./babel src --presets react --out-dir static
and now i get src doesn't exist

Thank you.

Angel

**Comment by arrmixer** [comment]
i tried this since it's a script 
 ./babel src --presets react --out-dir static
and not i get src doesn't exist

**Comment by arrmixer** [comment]
I got it to work via the script section in the package.json:
"build": "babel src --presets react --out-dir static"

**Comment by vasansr** [comment]
Yes, that's one way to get it to work. The other options are:

1. Use the complete path, as it is written in the book:

`$ node_modules/.bin/babel src --presets react --out-dir static
`

2. Install babel globally, in this case babel command line will be in your path (this option is not recommended since we'll soon replace the command-line with an entry in package.json as you have done)

`sudo npm install -g babel-cli`

**Comment by arrmixer** [comment]
Question was it your intention for us to install babel globally first for the command to work? 

Is that why the bash terminal didn't recognized the bagel command for me? 

Angel

**Comment by vasansr** [comment]
No, the intention was to use the full path. Not many folks realize that this can be done using the `node_modules/.bin` prefix where all the commands are available. Installing globally doesn't make sense at all, though it is an option. Using package.json is the way to go, and since you figured that out, my job is done ;-)

**Comment by arrmixer** [comment]
Ah okay! Make sense. Thank you 😊.
